// frontend/src/components/Pagination.vue
<script setup>
import { useRouteQuery } from '@/composables/useRouteQuery'
import { usePagination } from '@/composables/usePagination'

const props = defineProps({
  page: { type: Object, required: true },
})

const { patchQuery } = useRouteQuery()
const { current, isFirst, isLast, hasPages, pages, totalPages } = usePagination(() => props.page)

// page 쿼리만 갱신(0이면 키 제거), 나머지 쿼리는 보존
function goTo(p) {
  if (p < 0 || p > totalPages.value - 1 || p === current.value) return
  patchQuery({ page: p === 0 ? undefined : p })
}

const btn =
  'min-w-9 rounded-md px-3 py-1.5 text-sm transition disabled:cursor-not-allowed disabled:opacity-40'
</script>

<template>
  <nav v-if="hasPages" class="mt-8 flex items-center justify-center gap-1" aria-label="페이지 이동">
    <button type="button" :class="btn" class="hover:bg-cream-100" :disabled="isFirst" @click="goTo(current - 1)">
      이전
    </button>
    <button
      v-for="p in pages"
      :key="p"
      type="button"
      :class="[btn, p === current ? 'bg-vinyl-black font-semibold text-cream-50' : 'hover:bg-cream-100']"
      :aria-current="p === current ? 'page' : undefined"
      @click="goTo(p)"
    >
      {{ p + 1 }}
    </button>
    <button type="button" :class="btn" class="hover:bg-cream-100" :disabled="isLast" @click="goTo(current + 1)">
      다음
    </button>
  </nav>
</template>

// frontend/src/components/common/Pagination.tsx
interface PaginationProps {
  /** 0-base. */
  page: number;
  totalPages: number;
  onChange: (page: number) => void;
  siblingCount?: number;
}

type PageItem = number | 'ellipsis';

/** 1-base 표시값 기준으로 첫/끝 페이지와 현재 페이지 주변만 남기고 나머지는 생략 표시한다. */
const buildPageItems = (current1: number, totalPages: number, siblingCount: number): PageItem[] => {
  const items: PageItem[] = [];
  const start = Math.max(2, current1 - siblingCount);
  const end = Math.min(totalPages - 1, current1 + siblingCount);

  items.push(1);
  if (start > 2) {
    items.push('ellipsis');
  }
  for (let page = start; page <= end; page += 1) {
    items.push(page);
  }
  if (end < totalPages - 1) {
    items.push('ellipsis');
  }
  if (totalPages > 1) {
    items.push(totalPages);
  }

  return items;
};

export function Pagination({ page, totalPages, onChange, siblingCount = 1 }: PaginationProps) {
  if (totalPages <= 1) {
    return null;
  }

  const current1 = page + 1;
  const items = buildPageItems(current1, totalPages, siblingCount);
  const buttonBase =
    'flex h-9 w-9 items-center justify-center rounded-md text-sm disabled:cursor-not-allowed disabled:opacity-40';

  return (
    <nav aria-label="페이지" className="flex items-center justify-center gap-1">
      <button
        type="button"
        className={`${buttonBase} text-content-muted hover:bg-surface-muted hover:text-content`}
        onClick={() => onChange(page - 1)}
        disabled={page === 0}
        aria-label="이전 페이지"
      >
        ‹
      </button>

      {items.map((item, index) =>
        item === 'ellipsis' ? (
          <span
            key={`ellipsis-${index}`}
            aria-hidden
            className="flex h-9 w-9 items-center justify-center text-sm text-content-subtle"
          >
            …
          </span>
        ) : (
          <button
            key={item}
            type="button"
            aria-current={item === current1 ? 'page' : undefined}
            className={`${buttonBase} ${
              item === current1 ? 'bg-content text-surface' : 'text-content hover:bg-surface-muted'
            }`}
            onClick={() => onChange(item - 1)}
          >
            {item}
          </button>
        ),
      )}

      <button
        type="button"
        className={`${buttonBase} text-content-muted hover:bg-surface-muted hover:text-content`}
        onClick={() => onChange(page + 1)}
        disabled={page >= totalPages - 1}
        aria-label="다음 페이지"
      >
        ›
      </button>
    </nav>
  );
}
